version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: capoeira_postgres
    environment:
      POSTGRES_DB: capoeira_db      
      POSTGRES_USER: ${POSTGRES_USER}         
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "5432:5432" 
